name: Build and Release Packages

on:
  push:
#    tags:
#      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-snap:
    name: Build Snap for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Qemu for multi arch
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo usermod -aG lxd $USER
          sudo lxd init --auto
          newgroup lxd

      - name: Build snap
        run: snapcraft pack

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: waagent-rs-${{ matrix.arch }}
          path: ./*.snap

  release:
    name: Release Snap to Snap Store
    needs: build-snap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Download Snap artifact
        uses: actions/download-artifact@v4
        with:
          name: waagent-rs-${{ matrix.arch }}
          path: ./snap-${{ matrix.arch }}

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Authenticate with Snap Store
        run: |
          echo "${{ secrets.SNAPCRAFT_LOGIN }}" > snap-login.json
          snapcraft login --with snap-login.json

      - name: Push Snap to Store
        run: snapcraft push ./snap-${{ matrix.arch }}/*.snap --release=stable

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.rpm
